Feature/typography
womenhackfornonprofits/london-cafes-django pull request #56
Opened 2016-12-23 18:22 UTC by nuria-gs

### ISSUE NUMBER
#51 Add in typography styles

### Labels
- IN REVIEW

### Describe the changes
Added simple-typography files in the sass folder and imported the files in styles.scss

### Screenshots (if appropriate)
"n/a" 

### Questions or comments (if any)
"n/a"

2016-12-23 19:31 UTC, lili2311 requested changes

2016-12-23 19:31 UTC, lili2311 commented on frontend/sass/style.scss
> +@import "_mixins.scss";
please can you rename this file to be `_custom-typography.scss`

2016-12-23 19:31 UTC, lili2311 commented
left a comment otherwise good to merge

2016-12-23 20:30 UTC, nuria-gs commented
File renamed

2016-12-23 23:41 UTC, lili2311 commented
It is not present in the pull request, please can you push the new renamed file?

2016-12-24 07:29 UTC, nuria-gs commented
Sorry, I didn't realize the renamed file was on the untracked list.

2016-12-24 11:08 UTC, lili2311 approved these changes

2016-12-24 11:08 UTC, lili2311 commented
merging ty!

2016-12-24 11:08 UTC, merged